### PR TITLE
Add project generating table of roles using asciidoctor

### PR DESCRIPTION
**Pull request by cmoulliard**
- Issue #151 
- Add project generating table of roles using asciidoctor with dummy files

### CODE REVIEW

**Comment by jacobdotcosta** [comment]
How can I test generating the documentation locally?

I'm not sure how to launch `mvn` to launch the process.

**Comment by cmoulliard** [comment]
> I'm not sure how to launch `mvn` to launch the process.

```
cd tooling
mvn clean package
java -jar ./target/playbook-doc-1.0-SNAPSHOT.jar ./etc/config.yml
```

**Comment by cmoulliard** [comment]
> I think it looks good for 1 folder. Have you thought about how to launch it for all the subfolders in the roles directory?

As we can include using asciidoctor files --> `include::{path}/README.adoc[]`, then we should be able to define a generic `all.adoc` including all the sub-folders. Ideally this file should be populated automatically

**Comment by jacobdotcosta** [comment]
LGTM

**Pull request merged**
