### PR TITLE
Fix : Issue 181

### PR DESCRIPTION
**Pull request by cmoulliard**
- Fix : #181
- By changing the jsonpath query to search about the secret containing as annotation `kubernetes.io/service-account.name']=='default'`, the problem dont exist anymore

### CODE REVIEW

**Comment by cmoulliard** [comment]
WDYT ? @jacobdotcosta

**Comment by cmoulliard** [comment]
!!!! The following resource should be also changed when the cluster is created as the namespace to be used is default and not kube-system

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: system:default:default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default

**Comment by jacobdotcosta** [comment]
I don't have much to say. If it worked I'm OK with the changes.

LGTM!

**Review by jacobdotcosta — APPROVED** [review]
LGTM

**Pull request merged**
