### PR TITLE
Split the k8s playbook into 2 files

### PR DESCRIPTION
**Pull request by cmoulliard**
Issue : #152 
- Split the k8s playbook into 2 files
- Allow to execute the misc roles using command : ansible-playbook kubernetes/ansible/k8s-misc.yml --limit ${VM_NAME} --tag "docker_registry"

### CODE REVIEW

**Comment by jacobdotcosta** [comment]
I think all role invocations in the `k8s_misc` playbook should also have the `never` tag, otherwise if the playbook is executed without tags all roles will be applied, WDYT @cmoulliard ?

**Comment by cmoulliard** [comment]
> all roles will be applied

We will not apply all the roles but some only

**Comment by cmoulliard** [comment]
> playbook should also have the `never` tag

Why ? What is the purpose of the tag `never` ?

**Comment by jacobdotcosta** [comment]
> > playbook should also have the `never` tag
> 
> Why ? What is the purpose of the tag `never` ?

Without the never tag, it you execute the playbook without tags the roles will be executed whereas with the never tag the role is only executed if the tag is explicitly added to the command line.

**Comment by cmoulliard** [comment]
> Without the never tag, it you execute the playbook without tags the roles will be executed whereas with the never tag the role is only executed if the tag is explicitly added to the command line.

So we will then keep the playbook as it has been defined as we will specify when needed the `misc role(s)` to be applied ?

**Pull request merged**
